workflows:
  medinote_free_build:
    name: Medinote Free CI Build
    environment:
      groups:
        - medinote_env
      flutter: stable
      vars:
        BASE_URL: $BASE_URL
        DEEPGRAM_API_KEY: $DEEPGRAM_API_KEY

    scripts:
      # Always start clean in CI
      - flutter clean

      # Create .env file dynamically
      - |
          echo "BASE_URL=$BASE_URL" >> .env
          echo "DEEPGRAM_API_KEY=$DEEPGRAM_API_KEY" >> .env
      
      # Get dependencies
      - flutter pub get

      # Force localization & flutter_gen generation
      - flutter gen-l10n

      - ls .dart_tool/flutter_gen/gen_l10n

      # Build outputs
      - flutter build apk --release
      - flutter build web

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/web/**
